//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 12:23:29 PM EST 
//


package org.editeur.ns.onix._3_0.reference;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List139.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List139"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SYM"/&gt;
 *     &lt;enumeration value="ACM"/&gt;
 *     &lt;enumeration value="AAP"/&gt;
 *     &lt;enumeration value="ADL"/&gt;
 *     &lt;enumeration value="ACB"/&gt;
 *     &lt;enumeration value="AKK"/&gt;
 *     &lt;enumeration value="ALB"/&gt;
 *     &lt;enumeration value="ALT"/&gt;
 *     &lt;enumeration value="AMZ"/&gt;
 *     &lt;enumeration value="ANR"/&gt;
 *     &lt;enumeration value="ANB"/&gt;
 *     &lt;enumeration value="APA"/&gt;
 *     &lt;enumeration value="APC"/&gt;
 *     &lt;enumeration value="ASD"/&gt;
 *     &lt;enumeration value="ASB"/&gt;
 *     &lt;enumeration value="AUD"/&gt;
 *     &lt;enumeration value="AUC"/&gt;
 *     &lt;enumeration value="ATK"/&gt;
 *     &lt;enumeration value="BDL"/&gt;
 *     &lt;enumeration value="BNO"/&gt;
 *     &lt;enumeration value="BDZ"/&gt;
 *     &lt;enumeration value="BBB"/&gt;
 *     &lt;enumeration value="BST"/&gt;
 *     &lt;enumeration value="MMM"/&gt;
 *     &lt;enumeration value="BIL"/&gt;
 *     &lt;enumeration value="BLG"/&gt;
 *     &lt;enumeration value="BJW"/&gt;
 *     &lt;enumeration value="BLA"/&gt;
 *     &lt;enumeration value="BLK"/&gt;
 *     &lt;enumeration value="GOS"/&gt;
 *     &lt;enumeration value="BKU"/&gt;
 *     &lt;enumeration value="BLD"/&gt;
 *     &lt;enumeration value="BCA"/&gt;
 *     &lt;enumeration value="BOO"/&gt;
 *     &lt;enumeration value="BSH"/&gt;
 *     &lt;enumeration value="BKP"/&gt;
 *     &lt;enumeration value="BRB"/&gt;
 *     &lt;enumeration value="BKM"/&gt;
 *     &lt;enumeration value="BKS"/&gt;
 *     &lt;enumeration value="BTP"/&gt;
 *     &lt;enumeration value="BKY"/&gt;
 *     &lt;enumeration value="BRD"/&gt;
 *     &lt;enumeration value="BRT"/&gt;
 *     &lt;enumeration value="CDL"/&gt;
 *     &lt;enumeration value="CDN"/&gt;
 *     &lt;enumeration value="CEB"/&gt;
 *     &lt;enumeration value="CHD"/&gt;
 *     &lt;enumeration value="CYM"/&gt;
 *     &lt;enumeration value="CMX"/&gt;
 *     &lt;enumeration value="COP"/&gt;
 *     &lt;enumeration value="CST"/&gt;
 *     &lt;enumeration value="CRB"/&gt;
 *     &lt;enumeration value="CVS"/&gt;
 *     &lt;enumeration value="CVM"/&gt;
 *     &lt;enumeration value="CYB"/&gt;
 *     &lt;enumeration value="DEM"/&gt;
 *     &lt;enumeration value="DSG"/&gt;
 *     &lt;enumeration value="DIL"/&gt;
 *     &lt;enumeration value="DYM"/&gt;
 *     &lt;enumeration value="EPA"/&gt;
 *     &lt;enumeration value="ERD"/&gt;
 *     &lt;enumeration value="ELC"/&gt;
 *     &lt;enumeration value="ESN"/&gt;
 *     &lt;enumeration value="EBC"/&gt;
 *     &lt;enumeration value="ECH"/&gt;
 *     &lt;enumeration value="ECI"/&gt;
 *     &lt;enumeration value="ELE"/&gt;
 *     &lt;enumeration value="ELB"/&gt;
 *     &lt;enumeration value="ELS"/&gt;
 *     &lt;enumeration value="ELL"/&gt;
 *     &lt;enumeration value="EMP"/&gt;
 *     &lt;enumeration value="ENH"/&gt;
 *     &lt;enumeration value="EPC"/&gt;
 *     &lt;enumeration value="FDB"/&gt;
 *     &lt;enumeration value="FIN"/&gt;
 *     &lt;enumeration value="FSP"/&gt;
 *     &lt;enumeration value="FLP"/&gt;
 *     &lt;enumeration value="FNC"/&gt;
 *     &lt;enumeration value="FOL"/&gt;
 *     &lt;enumeration value="FRY"/&gt;
 *     &lt;enumeration value="GMS"/&gt;
 *     &lt;enumeration value="GLO"/&gt;
 *     &lt;enumeration value="GOO"/&gt;
 *     &lt;enumeration value="HST"/&gt;
 *     &lt;enumeration value="HMV"/&gt;
 *     &lt;enumeration value="HMD"/&gt;
 *     &lt;enumeration value="IMM"/&gt;
 *     &lt;enumeration value="IND"/&gt;
 *     &lt;enumeration value="IBS"/&gt;
 *     &lt;enumeration value="IZN"/&gt;
 *     &lt;enumeration value="JBH"/&gt;
 *     &lt;enumeration value="JSM"/&gt;
 *     &lt;enumeration value="KMT"/&gt;
 *     &lt;enumeration value="KID"/&gt;
 *     &lt;enumeration value="KPV"/&gt;
 *     &lt;enumeration value="KNB"/&gt;
 *     &lt;enumeration value="KNO"/&gt;
 *     &lt;enumeration value="KBO"/&gt;
 *     &lt;enumeration value="KOO"/&gt;
 *     &lt;enumeration value="KOR"/&gt;
 *     &lt;enumeration value="KRG"/&gt;
 *     &lt;enumeration value="LTP"/&gt;
 *     &lt;enumeration value="LWE"/&gt;
 *     &lt;enumeration value="MAC"/&gt;
 *     &lt;enumeration value="MAG"/&gt;
 *     &lt;enumeration value="MKS"/&gt;
 *     &lt;enumeration value="MAT"/&gt;
 *     &lt;enumeration value="MMS"/&gt;
 *     &lt;enumeration value="ADP"/&gt;
 *     &lt;enumeration value="MCR"/&gt;
 *     &lt;enumeration value="MSF"/&gt;
 *     &lt;enumeration value="MOF"/&gt;
 *     &lt;enumeration value="MRR"/&gt;
 *     &lt;enumeration value="MTC"/&gt;
 *     &lt;enumeration value="MYB"/&gt;
 *     &lt;enumeration value="MYI"/&gt;
 *     &lt;enumeration value="NTR"/&gt;
 *     &lt;enumeration value="NXT"/&gt;
 *     &lt;enumeration value="NUM"/&gt;
 *     &lt;enumeration value="OFD"/&gt;
 *     &lt;enumeration value="OFM"/&gt;
 *     &lt;enumeration value="OLF"/&gt;
 *     &lt;enumeration value="OVD"/&gt;
 *     &lt;enumeration value="OYS"/&gt;
 *     &lt;enumeration value="PST"/&gt;
 *     &lt;enumeration value="PTS"/&gt;
 *     &lt;enumeration value="PTC"/&gt;
 *     &lt;enumeration value="PLY"/&gt;
 *     &lt;enumeration value="POK"/&gt;
 *     &lt;enumeration value="PTB"/&gt;
 *     &lt;enumeration value="RDB"/&gt;
 *     &lt;enumeration value="RCL"/&gt;
 *     &lt;enumeration value="RST"/&gt;
 *     &lt;enumeration value="RET"/&gt;
 *     &lt;enumeration value="RTZ"/&gt;
 *     &lt;enumeration value="RMB"/&gt;
 *     &lt;enumeration value="RBD"/&gt;
 *     &lt;enumeration value="SGR"/&gt;
 *     &lt;enumeration value="SAF"/&gt;
 *     &lt;enumeration value="SFW"/&gt;
 *     &lt;enumeration value="SNS"/&gt;
 *     &lt;enumeration value="SCR"/&gt;
 *     &lt;enumeration value="SLF"/&gt;
 *     &lt;enumeration value="SEQ"/&gt;
 *     &lt;enumeration value="SBT"/&gt;
 *     &lt;enumeration value="SKB"/&gt;
 *     &lt;enumeration value="SMW"/&gt;
 *     &lt;enumeration value="SNY"/&gt;
 *     &lt;enumeration value="STP"/&gt;
 *     &lt;enumeration value="STT"/&gt;
 *     &lt;enumeration value="SKK"/&gt;
 *     &lt;enumeration value="SPL"/&gt;
 *     &lt;enumeration value="SUP"/&gt;
 *     &lt;enumeration value="SSK"/&gt;
 *     &lt;enumeration value="TRG"/&gt;
 *     &lt;enumeration value="TES"/&gt;
 *     &lt;enumeration value="TEA"/&gt;
 *     &lt;enumeration value="TOL"/&gt;
 *     &lt;enumeration value="TSR"/&gt;
 *     &lt;enumeration value="TSO"/&gt;
 *     &lt;enumeration value="TXR"/&gt;
 *     &lt;enumeration value="UBH"/&gt;
 *     &lt;enumeration value="VRG"/&gt;
 *     &lt;enumeration value="WHS"/&gt;
 *     &lt;enumeration value="WTR"/&gt;
 *     &lt;enumeration value="WLM"/&gt;
 *     &lt;enumeration value="WST"/&gt;
 *     &lt;enumeration value="WHT"/&gt;
 *     &lt;enumeration value="WLS"/&gt;
 *     &lt;enumeration value="WLW"/&gt;
 *     &lt;enumeration value="YOU"/&gt;
 *     &lt;enumeration value="ZVV"/&gt;
 *     &lt;enumeration value="PUB"/&gt;
 *     &lt;enumeration value="ZZZ"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List139")
@XmlEnum
public enum List139 {

    SYM,
    ACM,

    /**
     * Academic and Professional Book Center (HK)
     * 
     */
    AAP,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    ADL,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    ACB,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    AKK,
    ALB,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    ALT,
    AMZ,
    ANR,
    ANB,
    APA,
    APC,
    ASD,
    ASB,
    AUD,
    AUC,
    ATK,

    /**
     * Deprecated
     * 
     */
    BDL,
    BNO,

    /**
     * www.bdbuzz.net, for use in ONIX 3.0 only
     * 
     */
    BDZ,
    BBB,
    BST,

    /**
     * Formerly 3M Cloud Library
     * 
     */
    MMM,

    /**
     * Deprecated
     * 
     */
    BIL,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    BLG,
    BJW,

    /**
     * Deprecated
     * 
     */
    BLA,
    BLK,

    /**
     * Formerly GoSpoken/Mobcast. Deprecated
     * 
     */
    GOS,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    BKU,

    /**
     * www.bolinda.com, for use in ONIX 3.0 only
     * 
     */
    BLD,
    BCA,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    BOO,
    BSH,
    BKP,

    /**
     * Deprecated
     * 
     */
    BRB,
    BKM,
    BKS,
    BTP,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    BKY,

    /**
     * Deprecated
     * 
     */
    BRD,

    /**
     * Deprecated
     * 
     */
    BRT,
    CDL,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    CDN,
    CEB,
    CHD,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    CYM,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    CMX,

    /**
     * Deprecated
     * 
     */
    COP,
    CST,
    CRB,
    CVS,

    /**
     * www.cvs-mediatheques.com
     * 
     */
    CVM,
    CYB,
    DEM,
    DSG,
    DIL,
    DYM,
    EPA,
    ERD,
    ELC,
    ESN,

    /**
     * www.ebooks.com
     * 
     */
    EBC,

    /**
     * Deprecated
     * 
     */
    ECH,
    ECI,
    ELE,
    ELB,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    ELS,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    ELL,
    EMP,
    ENH,

    /**
     * www.getepic.com
     * 
     */
    EPC,
    FDB,
    FIN,
    FSP,
    FLP,
    FNC,
    FOL,
    FRY,
    GMS,
    GLO,
    GOO,

    /**
     * Deprecated
     * 
     */
    HST,
    HMV,
    HMD,
    IMM,
    IND,

    /**
     * www.ibs.it, for use in ONIX 3.0 only
     * 
     */
    IBS,
    IZN,
    JBH,
    JSM,
    KMT,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    KID,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    KPV,
    KNB,

    /**
     * Deprecate
     * 
     */
    KNO,
    KBO,
    KOO,
    KOR,
    KRG,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    LTP,
    LWE,
    MAC,
    MAG,
    MKS,
    MAT,

    /**
     * Also known as Media World
     * 
     */
    MMS,
    ADP,
    MCR,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    MSF,
    MOF,
    MRR,
    MTC,

    /**
     * Deprecated
     * 
     */
    MYB,
    MYI,
    NTR,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    NXT,
    NUM,
    OFD,
    OFM,
    OLF,
    OVD,

    /**
     * Deprecated
     * 
     */
    OYS,

    /**
     * Deprecated
     * 
     */
    PST,
    PTS,
    PTC,
    PLY,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    POK,
    PTB,

    /**
     * Deprecated
     * 
     */
    RDB,
    RCL,
    RST,
    RET,
    RTZ,

    /**
     * Deprecated
     * 
     */
    RMB,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    RBD,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    SGR,
    SAF,
    SFW,
    SNS,
    SCR,
    SLF,
    SEQ,
    SBT,
    SKB,
    SMW,
    SNY,
    STP,
    STT,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    SKK,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    SPL,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    SUP,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    SSK,
    TRG,
    TES,
    TEA,
    TOL,
    TSR,
    TSO,

    /**
     * Deprecated
     * 
     */
    TXR,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    UBH,

    /**
     * Deprecated
     * 
     */
    VRG,
    WHS,
    WTR,
    WLM,
    WST,
    WHT,
    WLS,
    WLW,

    /**
     * youboox.fr
     * 
     */
    YOU,

    /**
     * Formerly Virgin Megastores (UK)
     * 
     */
    ZVV,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    PUB,

    /**
     * Include retailer name in <SalesOutletName>
     * 
     */
    ZZZ;

    public String value() {
        return name();
    }

    public static List139 fromValue(String v) {
        return valueOf(v);
    }

}
