//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 12:23:29 PM EST 
//


package org.editeur.ns.onix._3_0.reference;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List21.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List21"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ABR"/&gt;
 *     &lt;enumeration value="ACT"/&gt;
 *     &lt;enumeration value="ADP"/&gt;
 *     &lt;enumeration value="ALT"/&gt;
 *     &lt;enumeration value="ANN"/&gt;
 *     &lt;enumeration value="BLL"/&gt;
 *     &lt;enumeration value="BLP"/&gt;
 *     &lt;enumeration value="BRL"/&gt;
 *     &lt;enumeration value="CMB"/&gt;
 *     &lt;enumeration value="CRI"/&gt;
 *     &lt;enumeration value="CSP"/&gt;
 *     &lt;enumeration value="DGO"/&gt;
 *     &lt;enumeration value="ENH"/&gt;
 *     &lt;enumeration value="ENL"/&gt;
 *     &lt;enumeration value="EXP"/&gt;
 *     &lt;enumeration value="FAC"/&gt;
 *     &lt;enumeration value="FST"/&gt;
 *     &lt;enumeration value="HRE"/&gt;
 *     &lt;enumeration value="ILL"/&gt;
 *     &lt;enumeration value="INT"/&gt;
 *     &lt;enumeration value="LTE"/&gt;
 *     &lt;enumeration value="MCP"/&gt;
 *     &lt;enumeration value="MDT"/&gt;
 *     &lt;enumeration value="MLL"/&gt;
 *     &lt;enumeration value="NED"/&gt;
 *     &lt;enumeration value="NUM"/&gt;
 *     &lt;enumeration value="PRB"/&gt;
 *     &lt;enumeration value="REV"/&gt;
 *     &lt;enumeration value="SCH"/&gt;
 *     &lt;enumeration value="SIG"/&gt;
 *     &lt;enumeration value="SMP"/&gt;
 *     &lt;enumeration value="SPE"/&gt;
 *     &lt;enumeration value="STU"/&gt;
 *     &lt;enumeration value="TCH"/&gt;
 *     &lt;enumeration value="UBR"/&gt;
 *     &lt;enumeration value="ULP"/&gt;
 *     &lt;enumeration value="UNN"/&gt;
 *     &lt;enumeration value="UXP"/&gt;
 *     &lt;enumeration value="VAR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List21")
@XmlEnum
public enum List21 {


    /**
     * Content has been shortened: use for abridged, shortened, concise, condensed
     * 
     */
    ABR,

    /**
     * Version of a play or script intended for use of those directly involved in a production, usually including full stage directions in addition to the text of the script
     * 
     */
    ACT,

    /**
     * Content has been adapted to serve a different purpose or audience, or from one medium to another: use for dramatization, novelization etc. Use <EditionStatement> to describe the exact nature of the adaptation
     * 
     */
    ADP,

    /**
     * Do not use. This code is now DEPRECATED, but is retained in the list for reasons of backwards compatibility
     * 
     */
    ALT,

    /**
     * Content is augmented by the addition of notes
     * 
     */
    ANN,

    /**
     * Both languages should be specified in the <Language> group. Use MLL for an edition in more than two languages
     * 
     */
    BLL,

    /**
     * Use only where the two languages are presented in parallel on facing pages, or in parallel columns of text on a single page (otherwise use BLL). Both languages should be specified in the <Language> group
     * 
     */
    BLP,

    /**
     * Braille edition
     * 
     */
    BRL,

    /**
     * An edition in which two or more works also published separately are combined in a single volume; AKA ‘omnibus’ edition (fr: ‘intégrale’)
     * 
     */
    CMB,

    /**
     * Content includes critical commentary on the text
     * 
     */
    CRI,

    /**
     * Content was compiled for a specified educational course
     * 
     */
    CSP,

    /**
     * A digital product that, at the time of publication, has or had no print counterpart and that is or was not expected to have a print counterpart for a reasonable time (recommended at least 30 days following publication)
     * 
     */
    DGO,

    /**
     * Use for e-publications that have been enhanced with additional text, speech, other audio, video, interactive or other content
     * 
     */
    ENH,

    /**
     * Content has been enlarged or expanded from that of a previous edition
     * 
     */
    ENL,

    /**
     * ‘Offensive’ content has been removed
     * 
     */
    EXP,

    /**
     * Exact reproduction of the content and format of a previous edition
     * 
     */
    FAC,

    /**
     * A collection of writings published in honor of a person, an institution or a society
     * 
     */
    FST,

    /**
     * Edition optimised for high readability, typically featuring colored or tinted page backgrounds to reduce contrast, extra letter, word and line spacing to reduce crowding and isolate individual words, simplified page layouts and an open, sans serif font (or occasionally, an unusual font design) intended to aid readability. Sometimes labelled ‘dyslexia-friendly’. See also code SMP if the text itself is simplified, and codes LTE or ULP if the type size is significantly larger than normal. For use in ONIX 3.0 only
     * 
     */
    HRE,

    /**
     * Content includes extensive illustrations which are not part of other editions
     * 
     */
    ILL,

    /**
     * A product aimed specifically at markets other than the country of original publication, usually titled as an ‘International edition’ and with specification and/or content changes
     * 
     */
    INT,

    /**
     * Large print edition, print sizes 14 to 19pt – see also ULP
     * 
     */
    LTE,

    /**
     * A printed edition in a type size too small to be read without a magnifying glass
     * 
     */
    MCP,

    /**
     * An edition published to coincide with the release of a film, TV program, or electronic game based on the same work. Use <EditionStatement> to describe the exact nature of the tie-in
     * 
     */
    MDT,

    /**
     * All languages should be specified in the ‘Language’ group. Use BLL for a bilingual edition
     * 
     */
    MLL,

    /**
     * Where no other information is given, or no other coded type or edition numbering is applicable
     * 
     */
    NED,

    /**
     * A limited edition in which each copy is individually numbered, and the actual number of copies is strictly limited. Use <EditionStatement> to give details of the number of copies printed
     * 
     */
    NUM,

    /**
     * In the US, a book that was previously bound, normally as a paperback, and has been rebound with a library-quality hardcover binding by a supplier other than the original publisher. See also the <Publisher> and <RelatedProduct> composites for other aspects of the treatment of prebound editions in ONIX
     * 
     */
    PRB,

    /**
     * Content has been revised from that of a previous edition (often used when there has been no corresponding increment in the edition number, or no edition numbering is available)
     * 
     */
    REV,

    /**
     * An edition intended specifically for use in schools
     * 
     */
    SCH,

    /**
     * Individually autographed by the author(s)
     * 
     */
    SIG,

    /**
     * An edition that uses simplified language (Finnish ‘Selkokirja’)
     * 
     */
    SMP,

    /**
     * Use for anniversary, collectors’, de luxe, gift, limited (but prefer codes NUM or UNN as appropriate), autographed (but prefer code SIG as appropriate) edition. Use <EditionStatement> to describe the exact nature of the special edition
     * 
     */
    SPE,

    /**
     * Where a text is available in both student and teacher’s editions
     * 
     */
    STU,

    /**
     * Where a text is available in both student and teacher’s editions; use also for instructor’s or leader’s editions, and for editions intended exclusively for educators where no specific student edition is available
     * 
     */
    TCH,

    /**
     * Where a title has also been published in an abridged edition; also for audiobooks, regardless of whether an abridged audio version also exists
     * 
     */
    UBR,

    /**
     * For print sizes 20pt and above, and with typefaces designed for the visually impaired – see also LTE
     * 
     */
    ULP,

    /**
     * A limited edition in which each copy is not individually numbered – but where the actual number of copies is strictly limited. Use <EditionStatement> to give details of the number of copies printed
     * 
     */
    UNN,

    /**
     * Content previously considered ‘offensive’ has been restored
     * 
     */
    UXP,

    /**
     * Content includes notes by various commentators, and/or includes and compares several variant texts of the same work
     * 
     */
    VAR;

    public String value() {
        return name();
    }

    public static List21 fromValue(String v) {
        return valueOf(v);
    }

}
