//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 12:23:29 PM EST 
//


package org.editeur.ns.onix._3_0.reference;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List98.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List98"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BLK"/&gt;
 *     &lt;enumeration value="BLU"/&gt;
 *     &lt;enumeration value="BRN"/&gt;
 *     &lt;enumeration value="BUR"/&gt;
 *     &lt;enumeration value="CEL"/&gt;
 *     &lt;enumeration value="CRE"/&gt;
 *     &lt;enumeration value="FCO"/&gt;
 *     &lt;enumeration value="FCS"/&gt;
 *     &lt;enumeration value="GLD"/&gt;
 *     &lt;enumeration value="GRN"/&gt;
 *     &lt;enumeration value="GRY"/&gt;
 *     &lt;enumeration value="MUL"/&gt;
 *     &lt;enumeration value="NAV"/&gt;
 *     &lt;enumeration value="ORG"/&gt;
 *     &lt;enumeration value="PNK"/&gt;
 *     &lt;enumeration value="PUR"/&gt;
 *     &lt;enumeration value="RED"/&gt;
 *     &lt;enumeration value="SKY"/&gt;
 *     &lt;enumeration value="SLV"/&gt;
 *     &lt;enumeration value="TAN"/&gt;
 *     &lt;enumeration value="TEA"/&gt;
 *     &lt;enumeration value="WHI"/&gt;
 *     &lt;enumeration value="YEL"/&gt;
 *     &lt;enumeration value="ZZZ"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List98")
@XmlEnum
public enum List98 {

    BLK,
    BLU,
    BRN,
    BUR,
    CEL,
    CRE,

    /**
     * Use <ProductFormFeatureDescription> to add brief details if required
     * 
     */
    FCO,

    /**
     * Use <ProductFormFeatureDescription> to add brief details if required
     * 
     */
    FCS,
    GLD,
    GRN,
    GRY,

    /**
     * Use <ProductFormFeatureDescription> to add brief details if required
     * 
     */
    MUL,
    NAV,
    ORG,
    PNK,
    PUR,
    RED,
    SKY,
    SLV,
    TAN,
    TEA,
    WHI,
    YEL,

    /**
     * Use <ProductFormFeatureDescription> to add brief details if required
     * 
     */
    ZZZ;

    public String value() {
        return name();
    }

    public static List98 fromValue(String v) {
        return valueOf(v);
    }

}
