//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 12:23:29 PM EST 
//


package org.editeur.ns.onix._3_0.reference;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List96.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List96"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AED"/&gt;
 *     &lt;enumeration value="AFA"/&gt;
 *     &lt;enumeration value="AFN"/&gt;
 *     &lt;enumeration value="ALL"/&gt;
 *     &lt;enumeration value="AMD"/&gt;
 *     &lt;enumeration value="ANG"/&gt;
 *     &lt;enumeration value="AOA"/&gt;
 *     &lt;enumeration value="ARS"/&gt;
 *     &lt;enumeration value="ATS"/&gt;
 *     &lt;enumeration value="AUD"/&gt;
 *     &lt;enumeration value="AWG"/&gt;
 *     &lt;enumeration value="AZN"/&gt;
 *     &lt;enumeration value="BAM"/&gt;
 *     &lt;enumeration value="BBD"/&gt;
 *     &lt;enumeration value="BDT"/&gt;
 *     &lt;enumeration value="BEF"/&gt;
 *     &lt;enumeration value="BGL"/&gt;
 *     &lt;enumeration value="BGN"/&gt;
 *     &lt;enumeration value="BHD"/&gt;
 *     &lt;enumeration value="BIF"/&gt;
 *     &lt;enumeration value="BMD"/&gt;
 *     &lt;enumeration value="BND"/&gt;
 *     &lt;enumeration value="BOB"/&gt;
 *     &lt;enumeration value="BRL"/&gt;
 *     &lt;enumeration value="BSD"/&gt;
 *     &lt;enumeration value="BTN"/&gt;
 *     &lt;enumeration value="BWP"/&gt;
 *     &lt;enumeration value="BYR"/&gt;
 *     &lt;enumeration value="BYN"/&gt;
 *     &lt;enumeration value="BZD"/&gt;
 *     &lt;enumeration value="CAD"/&gt;
 *     &lt;enumeration value="CDF"/&gt;
 *     &lt;enumeration value="CHF"/&gt;
 *     &lt;enumeration value="CLP"/&gt;
 *     &lt;enumeration value="CNY"/&gt;
 *     &lt;enumeration value="COP"/&gt;
 *     &lt;enumeration value="CRC"/&gt;
 *     &lt;enumeration value="CSD"/&gt;
 *     &lt;enumeration value="CUC"/&gt;
 *     &lt;enumeration value="CUP"/&gt;
 *     &lt;enumeration value="CVE"/&gt;
 *     &lt;enumeration value="CYP"/&gt;
 *     &lt;enumeration value="CZK"/&gt;
 *     &lt;enumeration value="DEM"/&gt;
 *     &lt;enumeration value="DJF"/&gt;
 *     &lt;enumeration value="DKK"/&gt;
 *     &lt;enumeration value="DOP"/&gt;
 *     &lt;enumeration value="DZD"/&gt;
 *     &lt;enumeration value="EEK"/&gt;
 *     &lt;enumeration value="EGP"/&gt;
 *     &lt;enumeration value="ERN"/&gt;
 *     &lt;enumeration value="ESP"/&gt;
 *     &lt;enumeration value="ETB"/&gt;
 *     &lt;enumeration value="EUR"/&gt;
 *     &lt;enumeration value="FIM"/&gt;
 *     &lt;enumeration value="FJD"/&gt;
 *     &lt;enumeration value="FKP"/&gt;
 *     &lt;enumeration value="FRF"/&gt;
 *     &lt;enumeration value="GBP"/&gt;
 *     &lt;enumeration value="GEL"/&gt;
 *     &lt;enumeration value="GHC"/&gt;
 *     &lt;enumeration value="GHS"/&gt;
 *     &lt;enumeration value="GIP"/&gt;
 *     &lt;enumeration value="GMD"/&gt;
 *     &lt;enumeration value="GNF"/&gt;
 *     &lt;enumeration value="GRD"/&gt;
 *     &lt;enumeration value="GTQ"/&gt;
 *     &lt;enumeration value="GWP"/&gt;
 *     &lt;enumeration value="GYD"/&gt;
 *     &lt;enumeration value="HKD"/&gt;
 *     &lt;enumeration value="HNL"/&gt;
 *     &lt;enumeration value="HRK"/&gt;
 *     &lt;enumeration value="HTG"/&gt;
 *     &lt;enumeration value="HUF"/&gt;
 *     &lt;enumeration value="IDR"/&gt;
 *     &lt;enumeration value="IEP"/&gt;
 *     &lt;enumeration value="ILS"/&gt;
 *     &lt;enumeration value="INR"/&gt;
 *     &lt;enumeration value="IQD"/&gt;
 *     &lt;enumeration value="IRR"/&gt;
 *     &lt;enumeration value="ISK"/&gt;
 *     &lt;enumeration value="ITL"/&gt;
 *     &lt;enumeration value="JMD"/&gt;
 *     &lt;enumeration value="JOD"/&gt;
 *     &lt;enumeration value="JPY"/&gt;
 *     &lt;enumeration value="KES"/&gt;
 *     &lt;enumeration value="KGS"/&gt;
 *     &lt;enumeration value="KHR"/&gt;
 *     &lt;enumeration value="KMF"/&gt;
 *     &lt;enumeration value="KPW"/&gt;
 *     &lt;enumeration value="KRW"/&gt;
 *     &lt;enumeration value="KWD"/&gt;
 *     &lt;enumeration value="KYD"/&gt;
 *     &lt;enumeration value="KZT"/&gt;
 *     &lt;enumeration value="LAK"/&gt;
 *     &lt;enumeration value="LBP"/&gt;
 *     &lt;enumeration value="LKR"/&gt;
 *     &lt;enumeration value="LRD"/&gt;
 *     &lt;enumeration value="LSL"/&gt;
 *     &lt;enumeration value="LTL"/&gt;
 *     &lt;enumeration value="LUF"/&gt;
 *     &lt;enumeration value="LVL"/&gt;
 *     &lt;enumeration value="LYD"/&gt;
 *     &lt;enumeration value="MAD"/&gt;
 *     &lt;enumeration value="MDL"/&gt;
 *     &lt;enumeration value="MGA"/&gt;
 *     &lt;enumeration value="MGF"/&gt;
 *     &lt;enumeration value="MKD"/&gt;
 *     &lt;enumeration value="MMK"/&gt;
 *     &lt;enumeration value="MNT"/&gt;
 *     &lt;enumeration value="MOP"/&gt;
 *     &lt;enumeration value="MRO"/&gt;
 *     &lt;enumeration value="MRU"/&gt;
 *     &lt;enumeration value="MTL"/&gt;
 *     &lt;enumeration value="MUR"/&gt;
 *     &lt;enumeration value="MVR"/&gt;
 *     &lt;enumeration value="MWK"/&gt;
 *     &lt;enumeration value="MXN"/&gt;
 *     &lt;enumeration value="MYR"/&gt;
 *     &lt;enumeration value="MZN"/&gt;
 *     &lt;enumeration value="NAD"/&gt;
 *     &lt;enumeration value="NGN"/&gt;
 *     &lt;enumeration value="NIO"/&gt;
 *     &lt;enumeration value="NLG"/&gt;
 *     &lt;enumeration value="NOK"/&gt;
 *     &lt;enumeration value="NPR"/&gt;
 *     &lt;enumeration value="NZD"/&gt;
 *     &lt;enumeration value="OMR"/&gt;
 *     &lt;enumeration value="PAB"/&gt;
 *     &lt;enumeration value="PEN"/&gt;
 *     &lt;enumeration value="PGK"/&gt;
 *     &lt;enumeration value="PHP"/&gt;
 *     &lt;enumeration value="PKR"/&gt;
 *     &lt;enumeration value="PLN"/&gt;
 *     &lt;enumeration value="PTE"/&gt;
 *     &lt;enumeration value="PYG"/&gt;
 *     &lt;enumeration value="QAR"/&gt;
 *     &lt;enumeration value="ROL"/&gt;
 *     &lt;enumeration value="RON"/&gt;
 *     &lt;enumeration value="RSD"/&gt;
 *     &lt;enumeration value="RUB"/&gt;
 *     &lt;enumeration value="RUR"/&gt;
 *     &lt;enumeration value="RWF"/&gt;
 *     &lt;enumeration value="SAR"/&gt;
 *     &lt;enumeration value="SBD"/&gt;
 *     &lt;enumeration value="SCR"/&gt;
 *     &lt;enumeration value="SDD"/&gt;
 *     &lt;enumeration value="SDG"/&gt;
 *     &lt;enumeration value="SEK"/&gt;
 *     &lt;enumeration value="SGD"/&gt;
 *     &lt;enumeration value="SHP"/&gt;
 *     &lt;enumeration value="SIT"/&gt;
 *     &lt;enumeration value="SKK"/&gt;
 *     &lt;enumeration value="SLL"/&gt;
 *     &lt;enumeration value="SOS"/&gt;
 *     &lt;enumeration value="SRD"/&gt;
 *     &lt;enumeration value="SRG"/&gt;
 *     &lt;enumeration value="STD"/&gt;
 *     &lt;enumeration value="STN"/&gt;
 *     &lt;enumeration value="SVC"/&gt;
 *     &lt;enumeration value="SYP"/&gt;
 *     &lt;enumeration value="SZL"/&gt;
 *     &lt;enumeration value="THB"/&gt;
 *     &lt;enumeration value="TJS"/&gt;
 *     &lt;enumeration value="TMM"/&gt;
 *     &lt;enumeration value="TMT"/&gt;
 *     &lt;enumeration value="TND"/&gt;
 *     &lt;enumeration value="TOP"/&gt;
 *     &lt;enumeration value="TPE"/&gt;
 *     &lt;enumeration value="TRL"/&gt;
 *     &lt;enumeration value="TRY"/&gt;
 *     &lt;enumeration value="TTD"/&gt;
 *     &lt;enumeration value="TWD"/&gt;
 *     &lt;enumeration value="TZS"/&gt;
 *     &lt;enumeration value="UAH"/&gt;
 *     &lt;enumeration value="UGX"/&gt;
 *     &lt;enumeration value="USD"/&gt;
 *     &lt;enumeration value="UYU"/&gt;
 *     &lt;enumeration value="UZS"/&gt;
 *     &lt;enumeration value="VEB"/&gt;
 *     &lt;enumeration value="VEF"/&gt;
 *     &lt;enumeration value="VES"/&gt;
 *     &lt;enumeration value="VND"/&gt;
 *     &lt;enumeration value="VUV"/&gt;
 *     &lt;enumeration value="WST"/&gt;
 *     &lt;enumeration value="XAF"/&gt;
 *     &lt;enumeration value="XCD"/&gt;
 *     &lt;enumeration value="XOF"/&gt;
 *     &lt;enumeration value="XPF"/&gt;
 *     &lt;enumeration value="YER"/&gt;
 *     &lt;enumeration value="YUM"/&gt;
 *     &lt;enumeration value="ZAR"/&gt;
 *     &lt;enumeration value="ZMK"/&gt;
 *     &lt;enumeration value="ZMW"/&gt;
 *     &lt;enumeration value="ZWD"/&gt;
 *     &lt;enumeration value="ZWL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List96")
@XmlEnum
public enum List96 {


    /**
     * United Arab Emirates
     * 
     */
    AED,

    /**
     * Afghanistan. DEPRECATED, replaced by AFN
     * 
     */
    AFA,

    /**
     * Afghanistan (prices normally quoted as integers)
     * 
     */
    AFN,

    /**
     * Albania (prices normally quoted as integers)
     * 
     */
    ALL,

    /**
     * Armenia (prices normally quoted as integers)
     * 
     */
    AMD,

    /**
     * Curaçao, Sint Maarten
     * 
     */
    ANG,

    /**
     * Angola
     * 
     */
    AOA,

    /**
     * Argentina
     * 
     */
    ARS,

    /**
     * Austria. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    ATS,

    /**
     * Australia, Christmas Island, Cocos (Keeling) Islands, Heard Island and McDonald Islands, Kiribati, Nauru, Norfolk Island, Tuvalu
     * 
     */
    AUD,

    /**
     * Aruba
     * 
     */
    AWG,

    /**
     * Azerbaijan
     * 
     */
    AZN,

    /**
     * Bosnia and Herzegovina
     * 
     */
    BAM,

    /**
     * Barbados
     * 
     */
    BBD,

    /**
     * Bangladesh
     * 
     */
    BDT,

    /**
     * Belgium. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    BEF,

    /**
     * DEPRECATED, replaced by BGN
     * 
     */
    BGL,

    /**
     * Bulgaria
     * 
     */
    BGN,

    /**
     * Bahrain (prices normally quoted with 3 decimal places)
     * 
     */
    BHD,

    /**
     * Burundi (prices normally quoted as integers)
     * 
     */
    BIF,

    /**
     * Bermuda
     * 
     */
    BMD,

    /**
     * Brunei Darussalam
     * 
     */
    BND,

    /**
     * Bolivia
     * 
     */
    BOB,

    /**
     * Brazil
     * 
     */
    BRL,

    /**
     * Bahamas
     * 
     */
    BSD,

    /**
     * Bhutan
     * 
     */
    BTN,

    /**
     * Botswana
     * 
     */
    BWP,

    /**
     * Belarus (prices normally quoted as integers). Deprecated – now replaced by new Belarussian Ruble (BYN): use only for historical prices that pre-date the introduction of the new Belarussian Ruble
     * 
     */
    BYR,

    /**
     * Belarus
     * 
     */
    BYN,

    /**
     * Belize
     * 
     */
    BZD,

    /**
     * Canada
     * 
     */
    CAD,

    /**
     * Congo (Democratic Republic of the)
     * 
     */
    CDF,

    /**
     * Switzerland, Liechtenstein
     * 
     */
    CHF,

    /**
     * Chile (prices normally quoted as integers)
     * 
     */
    CLP,

    /**
     * China
     * 
     */
    CNY,

    /**
     * Colombia (prices normally quoted as integers)
     * 
     */
    COP,

    /**
     * Costa Rica (prices normally quoted as integers)
     * 
     */
    CRC,

    /**
     * Deprecated, replaced by RSD
     * 
     */
    CSD,

    /**
     * Cuba (alternative currency)
     * 
     */
    CUC,

    /**
     * Cuba
     * 
     */
    CUP,

    /**
     * Cabo Verde (prices normally quoted as integers)
     * 
     */
    CVE,

    /**
     * Cyprus. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    CYP,

    /**
     * Czechia
     * 
     */
    CZK,

    /**
     * Germany. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    DEM,

    /**
     * Djibouti (prices normally quoted as integers)
     * 
     */
    DJF,

    /**
     * Denmark, Faroe Islands, Greenland
     * 
     */
    DKK,

    /**
     * Dominican Republic
     * 
     */
    DOP,

    /**
     * Algeria
     * 
     */
    DZD,

    /**
     * Estonia.Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    EEK,

    /**
     * Egypt
     * 
     */
    EGP,

    /**
     * Eritrea
     * 
     */
    ERN,

    /**
     * Spain. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro (prices normally quoted as integers)
     * 
     */
    ESP,

    /**
     * Ethiopia
     * 
     */
    ETB,

    /**
     * Eurozone: Andorra, Austria, Belgium, Cyprus, Estonia, Finland, France, Fr Guiana, Fr S Territories, Germany, Greece, Guadeloupe, Holy See (Vatican City), Ireland, Italy, Latvia, Lithuania, Luxembourg, Martinique, Malta, Mayotte, Monaco, Montenegro, Netherlands, Portugal, Réunion, St Barthelemy, St Martin, St Pierre and Miquelon, San Marino, Slovakia, Slovenia, Spain
     * 
     */
    EUR,

    /**
     * Finland. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    FIM,

    /**
     * Fiji
     * 
     */
    FJD,

    /**
     * Falkland Islands (Malvinas)
     * 
     */
    FKP,

    /**
     * France. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    FRF,

    /**
     * United Kingdom, Isle of Man, Channel Islands, South Georgia, South Sandwich Islands, British Indian Ocean Territory (de jure)
     * 
     */
    GBP,

    /**
     * Georgia
     * 
     */
    GEL,

    /**
     * Deprecated, replaced by GHS
     * 
     */
    GHC,

    /**
     * Ghana
     * 
     */
    GHS,

    /**
     * Gibraltar
     * 
     */
    GIP,

    /**
     * Gambia
     * 
     */
    GMD,

    /**
     * Guinea (prices normally quoted as integers)
     * 
     */
    GNF,

    /**
     * Greece. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    GRD,

    /**
     * Guatemala
     * 
     */
    GTQ,

    /**
     * Now replaced by the CFA Franc BCEAO XOF use only for historical prices that pre-date use of the CFA Franc
     * 
     */
    GWP,

    /**
     * Guyana (prices normally quoted as integers)
     * 
     */
    GYD,

    /**
     * Hong Kong
     * 
     */
    HKD,

    /**
     * Honduras
     * 
     */
    HNL,

    /**
     * Croatia
     * 
     */
    HRK,

    /**
     * Haiti
     * 
     */
    HTG,

    /**
     * Hungary (prices normally quoted as integers)
     * 
     */
    HUF,

    /**
     * Indonesia (prices normally quoted as integers)
     * 
     */
    IDR,

    /**
     * Ireland. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    IEP,

    /**
     * Israel
     * 
     */
    ILS,

    /**
     * India, Bhutan (prices normally quoted as integers)
     * 
     */
    INR,

    /**
     * Iraq (prices normally quoted as integers)
     * 
     */
    IQD,

    /**
     * Iran (Islamic Republic of) (prices normally quoted as integers)
     * 
     */
    IRR,

    /**
     * Iceland (prices normally quoted as integers)
     * 
     */
    ISK,

    /**
     * Italy. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro (prices normally quoted as integers)
     * 
     */
    ITL,

    /**
     * Jamaica
     * 
     */
    JMD,

    /**
     * Jordan (prices normally quoted with 3 decimal places)
     * 
     */
    JOD,

    /**
     * Japan (prices normally quoted as integers)
     * 
     */
    JPY,

    /**
     * Kenya
     * 
     */
    KES,

    /**
     * Kyrgyzstan
     * 
     */
    KGS,

    /**
     * Cambodia
     * 
     */
    KHR,

    /**
     * Comoros (prices normally quoted as integers)
     * 
     */
    KMF,

    /**
     * Korea (Democratic People’s Republic of) (prices normally quoted as integers)
     * 
     */
    KPW,

    /**
     * Korea (Republic of) (prices normally quoted as integers)
     * 
     */
    KRW,

    /**
     * Kuwait (prices normally quoted with 3 decimal places)
     * 
     */
    KWD,

    /**
     * Cayman Islands
     * 
     */
    KYD,

    /**
     * Kazakstan
     * 
     */
    KZT,

    /**
     * Lao People’s Democratic Republic (prices normally quoted as integers)
     * 
     */
    LAK,

    /**
     * Lebanon (prices normally quoted as integers)
     * 
     */
    LBP,

    /**
     * Sri Lanka
     * 
     */
    LKR,

    /**
     * Liberia
     * 
     */
    LRD,

    /**
     * Lesotho
     * 
     */
    LSL,

    /**
     * Lithuania. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    LTL,

    /**
     * Luxembourg. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro (prices normally quoted as integers)
     * 
     */
    LUF,

    /**
     * Latvia. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    LVL,

    /**
     * Libyan Arab Jamahiriya (prices normally quoted with 3 decimal places)
     * 
     */
    LYD,

    /**
     * Morocco, Western Sahara
     * 
     */
    MAD,

    /**
     * Moldova, Republic of
     * 
     */
    MDL,

    /**
     * Madagascar (prices normally quoted with 0 or 1 decimal place – 1 iraimbilanja = Ar0.2)
     * 
     */
    MGA,

    /**
     * Now replaced by the Ariary (MGA) (prices normally quoted as integers)
     * 
     */
    MGF,

    /**
     * North Macedonia (formerly FYR Macedonia)
     * 
     */
    MKD,

    /**
     * Myanmar (prices normally quoted as integers)
     * 
     */
    MMK,

    /**
     * Mongolia (prices normally quoted as integers)
     * 
     */
    MNT,

    /**
     * Macau
     * 
     */
    MOP,

    /**
     * Mauritania (prices normally quoted with 0 or 1 decimal place – 1 khoums = UM0.2). Was interchangeable with MRU (New) Ouguiya at rate of 10:1 until June 2018. DEPRECATED, use MRU instead
     * 
     */
    MRO,

    /**
     * Mauritania (prices normally quoted with 0 or 1 decimal place – 1 khoums = UM0.2). Replaced MRO (old) Ouguiya at rate of 10:1 in June 2018. For use in ONIX 3.0 only
     * 
     */
    MRU,

    /**
     * Malta. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    MTL,

    /**
     * Mauritius (prices normally quoted as integers)
     * 
     */
    MUR,

    /**
     * Maldives
     * 
     */
    MVR,

    /**
     * Malawi
     * 
     */
    MWK,

    /**
     * Mexico
     * 
     */
    MXN,

    /**
     * Malaysia
     * 
     */
    MYR,

    /**
     * Mozambique
     * 
     */
    MZN,

    /**
     * Namibia
     * 
     */
    NAD,

    /**
     * Nigeria
     * 
     */
    NGN,

    /**
     * Nicaragua
     * 
     */
    NIO,

    /**
     * Netherlands. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    NLG,

    /**
     * Norway, Bouvet Island, Svalbard and Jan Mayen
     * 
     */
    NOK,

    /**
     * Nepal
     * 
     */
    NPR,

    /**
     * New Zealand, Cook Islands, Niue, Pitcairn, Tokelau
     * 
     */
    NZD,

    /**
     * Oman (prices normally quoted with 3 decimal places)
     * 
     */
    OMR,

    /**
     * Panama
     * 
     */
    PAB,

    /**
     * Peru (formerly Nuevo Sol)
     * 
     */
    PEN,

    /**
     * Papua New Guinea
     * 
     */
    PGK,

    /**
     * Philippines
     * 
     */
    PHP,

    /**
     * Pakistan (prices normally quoted as integers)
     * 
     */
    PKR,

    /**
     * Poland
     * 
     */
    PLN,

    /**
     * Portugal. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    PTE,

    /**
     * Paraguay (prices normally quoted as integers)
     * 
     */
    PYG,

    /**
     * Qatar
     * 
     */
    QAR,

    /**
     * Deprecated, replaced by RON
     * 
     */
    ROL,

    /**
     * Romania
     * 
     */
    RON,

    /**
     * Serbia (prices normally quoted as integers)
     * 
     */
    RSD,

    /**
     * Russian Federation
     * 
     */
    RUB,

    /**
     * DEPRECATED, replaced by RUB
     * 
     */
    RUR,

    /**
     * Rwanda (prices normally quoted as integers)
     * 
     */
    RWF,

    /**
     * Saudi Arabia
     * 
     */
    SAR,

    /**
     * Solomon Islands
     * 
     */
    SBD,

    /**
     * Seychelles
     * 
     */
    SCR,

    /**
     * Now replaced by the Sudanese Pound (SDG)
     * 
     */
    SDD,

    /**
     * Sudan
     * 
     */
    SDG,

    /**
     * Sweden
     * 
     */
    SEK,

    /**
     * Singapore
     * 
     */
    SGD,

    /**
     * Saint Helena
     * 
     */
    SHP,

    /**
     * Slovenia. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    SIT,

    /**
     * Slovakia. Now replaced by the Euro (EUR). Deprecated – use only for historical prices that pre-date the introduction of the Euro
     * 
     */
    SKK,

    /**
     * Sierra Leone (prices normally quoted as integers)
     * 
     */
    SLL,

    /**
     * Somalia (prices normally quoted as integers)
     * 
     */
    SOS,

    /**
     * Suriname
     * 
     */
    SRD,

    /**
     * DEPRECATED, replaced by SRD
     * 
     */
    SRG,

    /**
     * São Tome and Principe (prices normally quoted as integers). Was interchangeable with STN (New) Dobra at rate of 1000:1 until June 2018. DEPRECATED, use STN instead
     * 
     */
    STD,

    /**
     * São Tome and Principe. Replaced STD (old) Dobra at rate of 1000:1 in June 2018. For use in ONIX 3.0 only
     * 
     */
    STN,

    /**
     * El Salvador
     * 
     */
    SVC,

    /**
     * Syrian Arab Republic (prices normally quoted as integers)
     * 
     */
    SYP,

    /**
     * Eswatini (formerly known as Swaziland)
     * 
     */
    SZL,

    /**
     * Thailand
     * 
     */
    THB,

    /**
     * Tajikistan
     * 
     */
    TJS,

    /**
     * Deprecated, replaced by TMT (prices normally quoted as integers)
     * 
     */
    TMM,

    /**
     * Turkmenistan
     * 
     */
    TMT,

    /**
     * Tunisia (prices normally quoted with 3 decimal places)
     * 
     */
    TND,

    /**
     * Tonga
     * 
     */
    TOP,

    /**
     * Deprecated. Timor-Leste now uses the US Dollar
     * 
     */
    TPE,

    /**
     * Deprecated, replaced by TRY (prices normally quoted as integers)
     * 
     */
    TRL,

    /**
     * Turkey, from 1 January 2005
     * 
     */
    TRY,

    /**
     * Trinidad and Tobago
     * 
     */
    TTD,

    /**
     * Taiwan (Province of China)
     * 
     */
    TWD,

    /**
     * Tanzania (United Republic of) (prices normally quoted as integers)
     * 
     */
    TZS,

    /**
     * Ukraine
     * 
     */
    UAH,

    /**
     * Uganda (prices normally quoted as integers)
     * 
     */
    UGX,

    /**
     * United States, American Samoa, Bonaire, Sint Eustatius and Saba, British Indian Ocean Territory, Ecuador, El Salvador, Guam, Haiti, Marshall Is, Micronesia (Federated States of), Northern Mariana Is, Palau, Panama, Puerto Rico, Timor-Leste, Turks and Caicos Is, US Minor Outlying Is, Virgin Is (British), Virgin Is (US)
     * 
     */
    USD,

    /**
     * Uruguay
     * 
     */
    UYU,

    /**
     * Uzbekistan (prices normally quoted as integers)
     * 
     */
    UZS,

    /**
     * Deprecated, replaced by VEF
     * 
     */
    VEB,

    /**
     * Venezuela (formerly Bolívar fuerte). Deprecated, replaced by VES
     * 
     */
    VEF,

    /**
     * Venezuela (replaced VEF from August 2018 at rate of 100,000:1). For use in ONIX 3.0 only
     * 
     */
    VES,

    /**
     * Viet Nam (prices normally quoted as integers)
     * 
     */
    VND,

    /**
     * Vanuatu (prices normally quoted as integers)
     * 
     */
    VUV,

    /**
     * Samoa
     * 
     */
    WST,

    /**
     * Cameroon, Central African Republic, Chad, Congo, Equatorial Guinea, Gabon (prices normally quoted as integers)
     * 
     */
    XAF,

    /**
     * Anguilla, Antigua and Barbuda, Dominica, Grenada, Montserrat, Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines
     * 
     */
    XCD,

    /**
     * Benin, Burkina Faso, Côte D’Ivoire, Guinea-Bissau, Mali, Niger, Senegal, Togo (prices normally quoted as integers)
     * 
     */
    XOF,

    /**
     * French Polynesia, New Caledonia, Wallis and Futuna (prices normally quoted as integers)
     * 
     */
    XPF,

    /**
     * Yemen (prices normally quoted as integers)
     * 
     */
    YER,

    /**
     * DEPRECATED, replaced by CSD
     * 
     */
    YUM,

    /**
     * South Africa, Namibia, Lesotho
     * 
     */
    ZAR,

    /**
     * Zambia. Deprecated, replaced with ZMW (prices normally quoted as integers)
     * 
     */
    ZMK,

    /**
     * Zambia
     * 
     */
    ZMW,

    /**
     * Deprecated, replaced with ZWL (prices normally quoted as integers)
     * 
     */
    ZWD,

    /**
     * Zimbabwe
     * 
     */
    ZWL;

    public String value() {
        return name();
    }

    public static List96 fromValue(String v) {
        return valueOf(v);
    }

}
