//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 12:23:29 PM EST 
//


package org.editeur.ns.onix._3_0.reference;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List17.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List17"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="A01"/&gt;
 *     &lt;enumeration value="A02"/&gt;
 *     &lt;enumeration value="A03"/&gt;
 *     &lt;enumeration value="A04"/&gt;
 *     &lt;enumeration value="A05"/&gt;
 *     &lt;enumeration value="A06"/&gt;
 *     &lt;enumeration value="A07"/&gt;
 *     &lt;enumeration value="A08"/&gt;
 *     &lt;enumeration value="A09"/&gt;
 *     &lt;enumeration value="A10"/&gt;
 *     &lt;enumeration value="A11"/&gt;
 *     &lt;enumeration value="A12"/&gt;
 *     &lt;enumeration value="A13"/&gt;
 *     &lt;enumeration value="A14"/&gt;
 *     &lt;enumeration value="A15"/&gt;
 *     &lt;enumeration value="A16"/&gt;
 *     &lt;enumeration value="A17"/&gt;
 *     &lt;enumeration value="A18"/&gt;
 *     &lt;enumeration value="A19"/&gt;
 *     &lt;enumeration value="A20"/&gt;
 *     &lt;enumeration value="A21"/&gt;
 *     &lt;enumeration value="A22"/&gt;
 *     &lt;enumeration value="A23"/&gt;
 *     &lt;enumeration value="A24"/&gt;
 *     &lt;enumeration value="A25"/&gt;
 *     &lt;enumeration value="A26"/&gt;
 *     &lt;enumeration value="A27"/&gt;
 *     &lt;enumeration value="A29"/&gt;
 *     &lt;enumeration value="A30"/&gt;
 *     &lt;enumeration value="A31"/&gt;
 *     &lt;enumeration value="A32"/&gt;
 *     &lt;enumeration value="A33"/&gt;
 *     &lt;enumeration value="A34"/&gt;
 *     &lt;enumeration value="A35"/&gt;
 *     &lt;enumeration value="A36"/&gt;
 *     &lt;enumeration value="A37"/&gt;
 *     &lt;enumeration value="A38"/&gt;
 *     &lt;enumeration value="A39"/&gt;
 *     &lt;enumeration value="A40"/&gt;
 *     &lt;enumeration value="A41"/&gt;
 *     &lt;enumeration value="A42"/&gt;
 *     &lt;enumeration value="A43"/&gt;
 *     &lt;enumeration value="A44"/&gt;
 *     &lt;enumeration value="A45"/&gt;
 *     &lt;enumeration value="A46"/&gt;
 *     &lt;enumeration value="A47"/&gt;
 *     &lt;enumeration value="A48"/&gt;
 *     &lt;enumeration value="A51"/&gt;
 *     &lt;enumeration value="A99"/&gt;
 *     &lt;enumeration value="B01"/&gt;
 *     &lt;enumeration value="B02"/&gt;
 *     &lt;enumeration value="B03"/&gt;
 *     &lt;enumeration value="B04"/&gt;
 *     &lt;enumeration value="B05"/&gt;
 *     &lt;enumeration value="B06"/&gt;
 *     &lt;enumeration value="B07"/&gt;
 *     &lt;enumeration value="B08"/&gt;
 *     &lt;enumeration value="B09"/&gt;
 *     &lt;enumeration value="B10"/&gt;
 *     &lt;enumeration value="B11"/&gt;
 *     &lt;enumeration value="B12"/&gt;
 *     &lt;enumeration value="B13"/&gt;
 *     &lt;enumeration value="B14"/&gt;
 *     &lt;enumeration value="B15"/&gt;
 *     &lt;enumeration value="B16"/&gt;
 *     &lt;enumeration value="B17"/&gt;
 *     &lt;enumeration value="B18"/&gt;
 *     &lt;enumeration value="B19"/&gt;
 *     &lt;enumeration value="B20"/&gt;
 *     &lt;enumeration value="B21"/&gt;
 *     &lt;enumeration value="B22"/&gt;
 *     &lt;enumeration value="B23"/&gt;
 *     &lt;enumeration value="B24"/&gt;
 *     &lt;enumeration value="B25"/&gt;
 *     &lt;enumeration value="B26"/&gt;
 *     &lt;enumeration value="B27"/&gt;
 *     &lt;enumeration value="B28"/&gt;
 *     &lt;enumeration value="B29"/&gt;
 *     &lt;enumeration value="B30"/&gt;
 *     &lt;enumeration value="B31"/&gt;
 *     &lt;enumeration value="B99"/&gt;
 *     &lt;enumeration value="C01"/&gt;
 *     &lt;enumeration value="C02"/&gt;
 *     &lt;enumeration value="C03"/&gt;
 *     &lt;enumeration value="C04"/&gt;
 *     &lt;enumeration value="C99"/&gt;
 *     &lt;enumeration value="D01"/&gt;
 *     &lt;enumeration value="D02"/&gt;
 *     &lt;enumeration value="D03"/&gt;
 *     &lt;enumeration value="D04"/&gt;
 *     &lt;enumeration value="D99"/&gt;
 *     &lt;enumeration value="E01"/&gt;
 *     &lt;enumeration value="E02"/&gt;
 *     &lt;enumeration value="E03"/&gt;
 *     &lt;enumeration value="E04"/&gt;
 *     &lt;enumeration value="E05"/&gt;
 *     &lt;enumeration value="E06"/&gt;
 *     &lt;enumeration value="E07"/&gt;
 *     &lt;enumeration value="E08"/&gt;
 *     &lt;enumeration value="E09"/&gt;
 *     &lt;enumeration value="E10"/&gt;
 *     &lt;enumeration value="E99"/&gt;
 *     &lt;enumeration value="F01"/&gt;
 *     &lt;enumeration value="F02"/&gt;
 *     &lt;enumeration value="F99"/&gt;
 *     &lt;enumeration value="Z01"/&gt;
 *     &lt;enumeration value="Z02"/&gt;
 *     &lt;enumeration value="Z03"/&gt;
 *     &lt;enumeration value="Z04"/&gt;
 *     &lt;enumeration value="Z98"/&gt;
 *     &lt;enumeration value="Z99"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List17")
@XmlEnum
public enum List17 {


    /**
     * Author of a textual work
     * 
     */
    @XmlEnumValue("A01")
    A_01("A01"),

    /**
     * With or as told to: ‘ghost’ or secondary author of a literary work (for clarity, should not be used for true ‘ghost’ authors who are not credited on the book and whose existence is secret)
     * 
     */
    @XmlEnumValue("A02")
    A_02("A02"),

    /**
     * Writer of screenplay or script (film or video)
     * 
     */
    @XmlEnumValue("A03")
    A_03("A03"),

    /**
     * Writer of libretto (opera): see also A31
     * 
     */
    @XmlEnumValue("A04")
    A_04("A04"),

    /**
     * Author of lyrics (song): see also A31
     * 
     */
    @XmlEnumValue("A05")
    A_05("A05"),

    /**
     * Composer of music
     * 
     */
    @XmlEnumValue("A06")
    A_06("A06"),

    /**
     * Visual artist when named as the primary creator of, eg, a book of reproductions of artworks
     * 
     */
    @XmlEnumValue("A07")
    A_07("A07"),

    /**
     * Photographer when named as the primary creator of, eg, a book of photographs
     * 
     */
    @XmlEnumValue("A08")
    A_08("A08"),

    /**
     * For example of editorial concept, of board game, etc
     * 
     */
    @XmlEnumValue("A09")
    A_09("A09"),
    @XmlEnumValue("A10")
    A_10("A10"),
    @XmlEnumValue("A11")
    A_11("A11"),

    /**
     * Artist when named as the creator of artwork which illustrates a text, or the originator (sometimes ‘penciller’ for collaborative art) of the artwork of a graphic novel or comic book
     * 
     */
    @XmlEnumValue("A12")
    A_12("A12"),

    /**
     * Photographer when named as the creator of photographs which illustrate a text
     * 
     */
    @XmlEnumValue("A13")
    A_13("A13"),

    /**
     * Author of text which accompanies art reproductions or photographs, or which is part of a graphic novel or comic book
     * 
     */
    @XmlEnumValue("A14")
    A_14("A14"),

    /**
     * Author of preface
     * 
     */
    @XmlEnumValue("A15")
    A_15("A15"),

    /**
     * Author of prologue
     * 
     */
    @XmlEnumValue("A16")
    A_16("A16"),

    /**
     * Author of summary
     * 
     */
    @XmlEnumValue("A17")
    A_17("A17"),

    /**
     * Author of supplement
     * 
     */
    @XmlEnumValue("A18")
    A_18("A18"),

    /**
     * Author of afterword
     * 
     */
    @XmlEnumValue("A19")
    A_19("A19"),

    /**
     * Author of notes or annotations: see also A29
     * 
     */
    @XmlEnumValue("A20")
    A_20("A20"),

    /**
     * Author of commentaries on the main text
     * 
     */
    @XmlEnumValue("A21")
    A_21("A21"),

    /**
     * Author of epilogue
     * 
     */
    @XmlEnumValue("A22")
    A_22("A22"),

    /**
     * Author of foreword
     * 
     */
    @XmlEnumValue("A23")
    A_23("A23"),

    /**
     * Author of introduction: see also A29
     * 
     */
    @XmlEnumValue("A24")
    A_24("A24"),

    /**
     * Author/compiler of footnotes
     * 
     */
    @XmlEnumValue("A25")
    A_25("A25"),

    /**
     * Author of memoir accompanying main text
     * 
     */
    @XmlEnumValue("A26")
    A_26("A26"),

    /**
     * Person who carried out experiments reported in the text
     * 
     */
    @XmlEnumValue("A27")
    A_27("A27"),

    /**
     * Author of introduction and notes: see also A20 and A24
     * 
     */
    @XmlEnumValue("A29")
    A_29("A29"),

    /**
     * Writer of computer programs ancillary to the text
     * 
     */
    @XmlEnumValue("A30")
    A_30("A30"),

    /**
     * Author of the textual content of a musical drama: see also A04 and A05
     * 
     */
    @XmlEnumValue("A31")
    A_31("A31"),

    /**
     * Author of additional contributions to the text
     * 
     */
    @XmlEnumValue("A32")
    A_32("A32"),

    /**
     * Author of appendix
     * 
     */
    @XmlEnumValue("A33")
    A_33("A33"),

    /**
     * Compiler of index
     * 
     */
    @XmlEnumValue("A34")
    A_34("A34"),
    @XmlEnumValue("A35")
    A_35("A35"),

    /**
     * Use also for the cover artist of a graphic novel or comic book if named separately
     * 
     */
    @XmlEnumValue("A36")
    A_36("A36"),

    /**
     * Responsible for preliminary work on which the work is based
     * 
     */
    @XmlEnumValue("A37")
    A_37("A37"),

    /**
     * Author of the first edition (usually of a standard work) who is not an author of the current edition
     * 
     */
    @XmlEnumValue("A38")
    A_38("A38"),

    /**
     * Maps drawn or otherwise contributed by
     * 
     */
    @XmlEnumValue("A39")
    A_39("A39"),

    /**
     * Use for secondary creators when separate persons are named as having respectively drawn and inked/colored/finished artwork, eg for a graphic novel or comic book. Use with A12 for ‘drawn by’. Use A40 for ‘finished by’, but prefer more specific codes A46 to A48 instead of A40 unless the more specific secondary roles are inappropriate, unclear or unavailable
     * 
     */
    @XmlEnumValue("A40")
    A_40("A40"),

    /**
     * Designer or paper engineer of die-cuts, press-outs or of pop-ups in a pop-up book, who may be different from the illustrator
     * 
     */
    @XmlEnumValue("A41")
    A_41("A41"),

    /**
     * Use where a standard work is being continued by somebody other than the original author
     * 
     */
    @XmlEnumValue("A42")
    A_42("A42"),
    @XmlEnumValue("A43")
    A_43("A43"),
    @XmlEnumValue("A44")
    A_44("A44"),

    /**
     * Writer of dialogue, captions in a comic book (following an outline by the primary writer)
     * 
     */
    @XmlEnumValue("A45")
    A_45("A45"),

    /**
     * Renders final comic book line art based on work of the illustrator or penciller. Preferred to code A40
     * 
     */
    @XmlEnumValue("A46")
    A_46("A46"),

    /**
     * Provides comic book color art and effects. Preferred to code A40
     * 
     */
    @XmlEnumValue("A47")
    A_47("A47"),

    /**
     * Creates comic book text balloons and other text elements (where this is a distinct role from script writer and/or illustrator)
     * 
     */
    @XmlEnumValue("A48")
    A_48("A48"),

    /**
     * Person or organization responsible for performing research on which the work is based. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("A51")
    A_51("A51"),

    /**
     * Other type of primary creator not specified above
     * 
     */
    @XmlEnumValue("A99")
    A_99("A99"),
    @XmlEnumValue("B01")
    B_01("B01"),
    @XmlEnumValue("B02")
    B_02("B02"),
    @XmlEnumValue("B03")
    B_03("B03"),
    @XmlEnumValue("B04")
    B_04("B04"),
    @XmlEnumValue("B05")
    B_05("B05"),
    @XmlEnumValue("B06")
    B_06("B06"),
    @XmlEnumValue("B07")
    B_07("B07"),

    /**
     * This code applies where a translator has provided a commentary on issues relating to the translation. If the translator has also provided a commentary on the work itself, codes B06 and A21 should be used
     * 
     */
    @XmlEnumValue("B08")
    B_08("B08"),

    /**
     * Name of a series editor when the product belongs to a series
     * 
     */
    @XmlEnumValue("B09")
    B_09("B09"),
    @XmlEnumValue("B10")
    B_10("B10"),
    @XmlEnumValue("B11")
    B_11("B11"),
    @XmlEnumValue("B12")
    B_12("B12"),
    @XmlEnumValue("B13")
    B_13("B13"),
    @XmlEnumValue("B14")
    B_14("B14"),
    @XmlEnumValue("B15")
    B_15("B15"),
    @XmlEnumValue("B16")
    B_16("B16"),

    /**
     * Usually the founder editor of a serial publication: Begruendet von
     * 
     */
    @XmlEnumValue("B17")
    B_17("B17"),
    @XmlEnumValue("B18")
    B_18("B18"),
    @XmlEnumValue("B19")
    B_19("B19"),

    /**
     * Use also for ‘advisory editor’, ‘series advisor’, ‘editorial consultant’ etc
     * 
     */
    @XmlEnumValue("B20")
    B_20("B20"),
    @XmlEnumValue("B21")
    B_21("B21"),
    @XmlEnumValue("B22")
    B_22("B22"),

    /**
     * In Europe, an expert editor who takes responsibility for the legal content of a collaborative law volume
     * 
     */
    @XmlEnumValue("B23")
    B_23("B23"),

    /**
     * An editor who is responsible for establishing the text used in an edition of a literary work, where this is recognised as a distinctive role (in Spain, ‘editor literario’)
     * 
     */
    @XmlEnumValue("B24")
    B_24("B24"),
    @XmlEnumValue("B25")
    B_25("B25"),

    /**
     * Responsible for the technical accuracy and language, may also be involved in coordinating and preparing technical material for publication
     * 
     */
    @XmlEnumValue("B26")
    B_26("B26"),
    @XmlEnumValue("B27")
    B_27("B27"),
    @XmlEnumValue("B28")
    B_28("B28"),

    /**
     * Responsible overall for the scientific content of the publication
     * 
     */
    @XmlEnumValue("B29")
    B_29("B29"),

    /**
     * For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("B30")
    B_30("B30"),

    /**
     * Editor of the first edition (usually of a standard work) who is not an editor of the current edition. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("B31")
    B_31("B31"),

    /**
     * Other type of adaptation or editing not specified above
     * 
     */
    @XmlEnumValue("B99")
    B_99("B99"),

    /**
     * For puzzles, directories, statistics, etc
     * 
     */
    @XmlEnumValue("C01")
    C_01("C01"),

    /**
     * For textual material (eg for an anthology)
     * 
     */
    @XmlEnumValue("C02")
    C_02("C02"),

    /**
     * Eg for a collection of photographs etc
     * 
     */
    @XmlEnumValue("C03")
    C_03("C03"),

    /**
     * Eg for an exhibition
     * 
     */
    @XmlEnumValue("C04")
    C_04("C04"),

    /**
     * Other type of compilation not specified above
     * 
     */
    @XmlEnumValue("C99")
    C_99("C99"),
    @XmlEnumValue("D01")
    D_01("D01"),
    @XmlEnumValue("D02")
    D_02("D02"),

    /**
     * Conductor of a musical performance
     * 
     */
    @XmlEnumValue("D03")
    D_03("D03"),

    /**
     * Of a dance performance. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("D04")
    D_04("D04"),

    /**
     * Other type of direction not specified above
     * 
     */
    @XmlEnumValue("D99")
    D_99("D99"),

    /**
     * Performer in a dramatized production (including a voice actor in an audio production)
     * 
     */
    @XmlEnumValue("E01")
    E_01("E01"),
    @XmlEnumValue("E02")
    E_02("E02"),

    /**
     * Where the narrator is a character in a dramatized production (including a voice actor in an audio production). For the ‘narrator’ of a non-dramatized audiobook, see code E07
     * 
     */
    @XmlEnumValue("E03")
    E_03("E03"),
    @XmlEnumValue("E04")
    E_04("E04"),

    /**
     * Singer etc
     * 
     */
    @XmlEnumValue("E05")
    E_05("E05"),
    @XmlEnumValue("E06")
    E_06("E06"),

    /**
     * Reader of recorded text, as in an audiobook
     * 
     */
    @XmlEnumValue("E07")
    E_07("E07"),

    /**
     * Name of a musical group in a performing role
     * 
     */
    @XmlEnumValue("E08")
    E_08("E08"),

    /**
     * Of a speech, lecture etc
     * 
     */
    @XmlEnumValue("E09")
    E_09("E09"),

    /**
     * Introduces and links other contributors and material, eg within a documentary
     * 
     */
    @XmlEnumValue("E10")
    E_10("E10"),

    /**
     * Other type of performer not specified above: use for a recorded performance which does not fit a category above, eg a performance by a stand-up comedian
     * 
     */
    @XmlEnumValue("E99")
    E_99("E99"),

    /**
     * Cinematographer, etc
     * 
     */
    @XmlEnumValue("F01")
    F_01("F01"),
    @XmlEnumValue("F02")
    F_02("F02"),

    /**
     * Other type of recording not specified above
     * 
     */
    @XmlEnumValue("F99")
    F_99("F99"),

    /**
     * May be associated with any contributor role, and placement should therefore be controlled by contributor sequence numbering
     * 
     */
    @XmlEnumValue("Z01")
    Z_01("Z01"),
    @XmlEnumValue("Z02")
    Z_02("Z02"),

    /**
     * For publication of laws, regulations, rulings etc. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Z03")
    Z_03("Z03"),

    /**
     * Use with <UnnamedPersons> code 02 as a ‘flag’ to indicate the publication is anonymously peer-reviewed. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Z04")
    Z_04("Z04"),

    /**
     * For use ONLY with ‘et al’ or ‘Various’ within <UnnamedPersons>, where the roles of the multiple contributors vary
     * 
     */
    @XmlEnumValue("Z98")
    Z_98("Z98"),

    /**
     * Other creative responsibility not falling within A to F above
     * 
     */
    @XmlEnumValue("Z99")
    Z_99("Z99");
    private final String value;

    List17(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static List17 fromValue(String v) {
        for (List17 c: List17 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
