//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 12:23:29 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ns.editeur.org/onix/3.0/reference", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.editeur.ns.onix._3_0.reference;
