//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 12:23:29 PM EST 
//


package org.editeur.ns.onix._3_0.reference;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}PriceIdentifier" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}PriceType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}PriceQualifier" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}EpubTechnicalProtection" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}PriceConstraint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}EpubLicense" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}PriceTypeDescription" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}PricePer" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}PriceCondition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}MinimumOrderQuantity" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}BatchBonus" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}DiscountCoded" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}Discount" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}PriceStatus" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;choice&gt;
 *               &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}PriceAmount"/&gt;
 *               &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}PriceCoded"/&gt;
 *             &lt;/choice&gt;
 *             &lt;choice minOccurs="0"&gt;
 *               &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}Tax" maxOccurs="unbounded"/&gt;
 *               &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}TaxExempt"/&gt;
 *             &lt;/choice&gt;
 *           &lt;/sequence&gt;
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}UnpricedItemType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}CurrencyCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}Territory" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}CurrencyZone" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}ComparisonProductPrice" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}PriceDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;sequence minOccurs="0"&gt;
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}PrintedOnProduct"/&gt;
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}PositionOnProduct" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://ns.editeur.org/onix/3.0/reference}generalAttributes"/&gt;
 *       &lt;attribute name="refname"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Price"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="shortname"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="price"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "priceIdentifier",
    "priceType",
    "priceQualifier",
    "epubTechnicalProtection",
    "priceConstraint",
    "epubLicense",
    "priceTypeDescription",
    "pricePer",
    "priceCondition",
    "minimumOrderQuantity",
    "batchBonus",
    "discountCoded",
    "discount",
    "priceStatus",
    "priceAmount",
    "priceCoded",
    "tax",
    "taxExempt",
    "unpricedItemType",
    "currencyCode",
    "territory",
    "currencyZone",
    "comparisonProductPrice",
    "priceDate",
    "printedOnProduct",
    "positionOnProduct"
})
@XmlRootElement(name = "Price")
public class Price {

    @XmlElement(name = "PriceIdentifier")
    protected List<PriceIdentifier> priceIdentifier;
    @XmlElement(name = "PriceType")
    protected PriceType priceType;
    @XmlElement(name = "PriceQualifier")
    protected PriceQualifier priceQualifier;
    @XmlElement(name = "EpubTechnicalProtection")
    protected List<EpubTechnicalProtection> epubTechnicalProtection;
    @XmlElement(name = "PriceConstraint")
    protected List<PriceConstraint> priceConstraint;
    @XmlElement(name = "EpubLicense")
    protected EpubLicense epubLicense;
    @XmlElement(name = "PriceTypeDescription")
    protected List<PriceTypeDescription> priceTypeDescription;
    @XmlElement(name = "PricePer")
    protected PricePer pricePer;
    @XmlElement(name = "PriceCondition")
    protected List<PriceCondition> priceCondition;
    @XmlElement(name = "MinimumOrderQuantity")
    protected MinimumOrderQuantity minimumOrderQuantity;
    @XmlElement(name = "BatchBonus")
    protected List<BatchBonus> batchBonus;
    @XmlElement(name = "DiscountCoded")
    protected List<DiscountCoded> discountCoded;
    @XmlElement(name = "Discount")
    protected List<Discount> discount;
    @XmlElement(name = "PriceStatus")
    protected PriceStatus priceStatus;
    @XmlElement(name = "PriceAmount")
    protected PriceAmount priceAmount;
    @XmlElement(name = "PriceCoded")
    protected PriceCoded priceCoded;
    @XmlElement(name = "Tax")
    protected List<Tax> tax;
    @XmlElement(name = "TaxExempt")
    protected TaxExempt taxExempt;
    @XmlElement(name = "UnpricedItemType")
    protected UnpricedItemType unpricedItemType;
    @XmlElement(name = "CurrencyCode")
    protected CurrencyCode currencyCode;
    @XmlElement(name = "Territory")
    protected Territory territory;
    @XmlElement(name = "CurrencyZone")
    protected CurrencyZone currencyZone;
    @XmlElement(name = "ComparisonProductPrice")
    protected List<ComparisonProductPrice> comparisonProductPrice;
    @XmlElement(name = "PriceDate")
    protected List<PriceDate> priceDate;
    @XmlElement(name = "PrintedOnProduct")
    protected PrintedOnProduct printedOnProduct;
    @XmlElement(name = "PositionOnProduct")
    protected PositionOnProduct positionOnProduct;
    @XmlAttribute(name = "refname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute(name = "shortname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute(name = "datestamp")
    protected String datestamp;
    @XmlAttribute(name = "sourcetype")
    protected String sourcetype;
    @XmlAttribute(name = "sourcename")
    protected String sourcename;

    /**
     * Gets the value of the priceIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priceIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriceIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PriceIdentifier }
     * 
     * 
     */
    public List<PriceIdentifier> getPriceIdentifier() {
        if (priceIdentifier == null) {
            priceIdentifier = new ArrayList<PriceIdentifier>();
        }
        return this.priceIdentifier;
    }

    /**
     * Gets the value of the priceType property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getPriceType() {
        return priceType;
    }

    /**
     * Sets the value of the priceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setPriceType(PriceType value) {
        this.priceType = value;
    }

    /**
     * Gets the value of the priceQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link PriceQualifier }
     *     
     */
    public PriceQualifier getPriceQualifier() {
        return priceQualifier;
    }

    /**
     * Sets the value of the priceQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceQualifier }
     *     
     */
    public void setPriceQualifier(PriceQualifier value) {
        this.priceQualifier = value;
    }

    /**
     * Gets the value of the epubTechnicalProtection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epubTechnicalProtection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEpubTechnicalProtection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EpubTechnicalProtection }
     * 
     * 
     */
    public List<EpubTechnicalProtection> getEpubTechnicalProtection() {
        if (epubTechnicalProtection == null) {
            epubTechnicalProtection = new ArrayList<EpubTechnicalProtection>();
        }
        return this.epubTechnicalProtection;
    }

    /**
     * Gets the value of the priceConstraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priceConstraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriceConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PriceConstraint }
     * 
     * 
     */
    public List<PriceConstraint> getPriceConstraint() {
        if (priceConstraint == null) {
            priceConstraint = new ArrayList<PriceConstraint>();
        }
        return this.priceConstraint;
    }

    /**
     * Gets the value of the epubLicense property.
     * 
     * @return
     *     possible object is
     *     {@link EpubLicense }
     *     
     */
    public EpubLicense getEpubLicense() {
        return epubLicense;
    }

    /**
     * Sets the value of the epubLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link EpubLicense }
     *     
     */
    public void setEpubLicense(EpubLicense value) {
        this.epubLicense = value;
    }

    /**
     * Gets the value of the priceTypeDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priceTypeDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriceTypeDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PriceTypeDescription }
     * 
     * 
     */
    public List<PriceTypeDescription> getPriceTypeDescription() {
        if (priceTypeDescription == null) {
            priceTypeDescription = new ArrayList<PriceTypeDescription>();
        }
        return this.priceTypeDescription;
    }

    /**
     * Gets the value of the pricePer property.
     * 
     * @return
     *     possible object is
     *     {@link PricePer }
     *     
     */
    public PricePer getPricePer() {
        return pricePer;
    }

    /**
     * Sets the value of the pricePer property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricePer }
     *     
     */
    public void setPricePer(PricePer value) {
        this.pricePer = value;
    }

    /**
     * Gets the value of the priceCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priceCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriceCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PriceCondition }
     * 
     * 
     */
    public List<PriceCondition> getPriceCondition() {
        if (priceCondition == null) {
            priceCondition = new ArrayList<PriceCondition>();
        }
        return this.priceCondition;
    }

    /**
     * Gets the value of the minimumOrderQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link MinimumOrderQuantity }
     *     
     */
    public MinimumOrderQuantity getMinimumOrderQuantity() {
        return minimumOrderQuantity;
    }

    /**
     * Sets the value of the minimumOrderQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinimumOrderQuantity }
     *     
     */
    public void setMinimumOrderQuantity(MinimumOrderQuantity value) {
        this.minimumOrderQuantity = value;
    }

    /**
     * Gets the value of the batchBonus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the batchBonus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBatchBonus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BatchBonus }
     * 
     * 
     */
    public List<BatchBonus> getBatchBonus() {
        if (batchBonus == null) {
            batchBonus = new ArrayList<BatchBonus>();
        }
        return this.batchBonus;
    }

    /**
     * Gets the value of the discountCoded property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discountCoded property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscountCoded().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DiscountCoded }
     * 
     * 
     */
    public List<DiscountCoded> getDiscountCoded() {
        if (discountCoded == null) {
            discountCoded = new ArrayList<DiscountCoded>();
        }
        return this.discountCoded;
    }

    /**
     * Gets the value of the discount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Discount }
     * 
     * 
     */
    public List<Discount> getDiscount() {
        if (discount == null) {
            discount = new ArrayList<Discount>();
        }
        return this.discount;
    }

    /**
     * Gets the value of the priceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PriceStatus }
     *     
     */
    public PriceStatus getPriceStatus() {
        return priceStatus;
    }

    /**
     * Sets the value of the priceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceStatus }
     *     
     */
    public void setPriceStatus(PriceStatus value) {
        this.priceStatus = value;
    }

    /**
     * Gets the value of the priceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link PriceAmount }
     *     
     */
    public PriceAmount getPriceAmount() {
        return priceAmount;
    }

    /**
     * Sets the value of the priceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceAmount }
     *     
     */
    public void setPriceAmount(PriceAmount value) {
        this.priceAmount = value;
    }

    /**
     * Gets the value of the priceCoded property.
     * 
     * @return
     *     possible object is
     *     {@link PriceCoded }
     *     
     */
    public PriceCoded getPriceCoded() {
        return priceCoded;
    }

    /**
     * Sets the value of the priceCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceCoded }
     *     
     */
    public void setPriceCoded(PriceCoded value) {
        this.priceCoded = value;
    }

    /**
     * Gets the value of the tax property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tax property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTax().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tax }
     * 
     * 
     */
    public List<Tax> getTax() {
        if (tax == null) {
            tax = new ArrayList<Tax>();
        }
        return this.tax;
    }

    /**
     * Gets the value of the taxExempt property.
     * 
     * @return
     *     possible object is
     *     {@link TaxExempt }
     *     
     */
    public TaxExempt getTaxExempt() {
        return taxExempt;
    }

    /**
     * Sets the value of the taxExempt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxExempt }
     *     
     */
    public void setTaxExempt(TaxExempt value) {
        this.taxExempt = value;
    }

    /**
     * Gets the value of the unpricedItemType property.
     * 
     * @return
     *     possible object is
     *     {@link UnpricedItemType }
     *     
     */
    public UnpricedItemType getUnpricedItemType() {
        return unpricedItemType;
    }

    /**
     * Sets the value of the unpricedItemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnpricedItemType }
     *     
     */
    public void setUnpricedItemType(UnpricedItemType value) {
        this.unpricedItemType = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCode }
     *     
     */
    public CurrencyCode getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCode }
     *     
     */
    public void setCurrencyCode(CurrencyCode value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the territory property.
     * 
     * @return
     *     possible object is
     *     {@link Territory }
     *     
     */
    public Territory getTerritory() {
        return territory;
    }

    /**
     * Sets the value of the territory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Territory }
     *     
     */
    public void setTerritory(Territory value) {
        this.territory = value;
    }

    /**
     * Gets the value of the currencyZone property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyZone }
     *     
     */
    public CurrencyZone getCurrencyZone() {
        return currencyZone;
    }

    /**
     * Sets the value of the currencyZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyZone }
     *     
     */
    public void setCurrencyZone(CurrencyZone value) {
        this.currencyZone = value;
    }

    /**
     * Gets the value of the comparisonProductPrice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comparisonProductPrice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComparisonProductPrice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComparisonProductPrice }
     * 
     * 
     */
    public List<ComparisonProductPrice> getComparisonProductPrice() {
        if (comparisonProductPrice == null) {
            comparisonProductPrice = new ArrayList<ComparisonProductPrice>();
        }
        return this.comparisonProductPrice;
    }

    /**
     * Gets the value of the priceDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priceDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriceDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PriceDate }
     * 
     * 
     */
    public List<PriceDate> getPriceDate() {
        if (priceDate == null) {
            priceDate = new ArrayList<PriceDate>();
        }
        return this.priceDate;
    }

    /**
     * Gets the value of the printedOnProduct property.
     * 
     * @return
     *     possible object is
     *     {@link PrintedOnProduct }
     *     
     */
    public PrintedOnProduct getPrintedOnProduct() {
        return printedOnProduct;
    }

    /**
     * Sets the value of the printedOnProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrintedOnProduct }
     *     
     */
    public void setPrintedOnProduct(PrintedOnProduct value) {
        this.printedOnProduct = value;
    }

    /**
     * Gets the value of the positionOnProduct property.
     * 
     * @return
     *     possible object is
     *     {@link PositionOnProduct }
     *     
     */
    public PositionOnProduct getPositionOnProduct() {
        return positionOnProduct;
    }

    /**
     * Sets the value of the positionOnProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionOnProduct }
     *     
     */
    public void setPositionOnProduct(PositionOnProduct value) {
        this.positionOnProduct = value;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
