//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 12:23:29 PM EST 
//


package org.editeur.ns.onix._3_0.reference;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}StockQuantityCodeType"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}StockQuantityCodeTypeName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}StockQuantityCode"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://ns.editeur.org/onix/3.0/reference}generalAttributes"/&gt;
 *       &lt;attribute name="refname"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="StockQuantityCoded"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="shortname"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="stockquantitycoded"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stockQuantityCodeType",
    "stockQuantityCodeTypeName",
    "stockQuantityCode"
})
@XmlRootElement(name = "StockQuantityCoded")
public class StockQuantityCoded {

    @XmlElement(name = "StockQuantityCodeType", required = true)
    protected StockQuantityCodeType stockQuantityCodeType;
    @XmlElement(name = "StockQuantityCodeTypeName")
    protected StockQuantityCodeTypeName stockQuantityCodeTypeName;
    @XmlElement(name = "StockQuantityCode", required = true)
    protected StockQuantityCode stockQuantityCode;
    @XmlAttribute(name = "refname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute(name = "shortname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute(name = "datestamp")
    protected String datestamp;
    @XmlAttribute(name = "sourcetype")
    protected String sourcetype;
    @XmlAttribute(name = "sourcename")
    protected String sourcename;

    /**
     * Gets the value of the stockQuantityCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link StockQuantityCodeType }
     *     
     */
    public StockQuantityCodeType getStockQuantityCodeType() {
        return stockQuantityCodeType;
    }

    /**
     * Sets the value of the stockQuantityCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StockQuantityCodeType }
     *     
     */
    public void setStockQuantityCodeType(StockQuantityCodeType value) {
        this.stockQuantityCodeType = value;
    }

    /**
     * Gets the value of the stockQuantityCodeTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link StockQuantityCodeTypeName }
     *     
     */
    public StockQuantityCodeTypeName getStockQuantityCodeTypeName() {
        return stockQuantityCodeTypeName;
    }

    /**
     * Sets the value of the stockQuantityCodeTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StockQuantityCodeTypeName }
     *     
     */
    public void setStockQuantityCodeTypeName(StockQuantityCodeTypeName value) {
        this.stockQuantityCodeTypeName = value;
    }

    /**
     * Gets the value of the stockQuantityCode property.
     * 
     * @return
     *     possible object is
     *     {@link StockQuantityCode }
     *     
     */
    public StockQuantityCode getStockQuantityCode() {
        return stockQuantityCode;
    }

    /**
     * Sets the value of the stockQuantityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StockQuantityCode }
     *     
     */
    public void setStockQuantityCode(StockQuantityCode value) {
        this.stockQuantityCode = value;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
